CREATE TABLE IF NOT EXISTS goods_receipts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  gr_number text UNIQUE NOT NULL,
  purchase_order_id uuid NOT NULL REFERENCES purchase_orders(id) ON DELETE RESTRICT,
  po_number text NOT NULL DEFAULT '',
  vendor_id text DEFAULT '',
  vendor_name text NOT NULL DEFAULT '',
  company_id uuid REFERENCES companies(id) ON DELETE SET NULL,
  received_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  inspected_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  receipt_date date NOT NULL DEFAULT CURRENT_DATE,
  delivery_receipt_number text DEFAULT '',
  receipt_type text NOT NULL DEFAULT 'partial' CHECK (receipt_type IN ('full','partial')),
  overall_condition text NOT NULL DEFAULT 'good' CHECK (overall_condition IN ('good','damaged','mixed')),
  warehouse_location text DEFAULT '',
  remarks text DEFAULT '',
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','confirmed','cancelled')),
  confirmed_at timestamptz,
  cancelled_at timestamptz,
  cancellation_reason text DEFAULT '',
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  deleted_at timestamptz
);